apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-mysql
spec:
  description: Deploy MySQL Database with initialization scripts.
  workspaces:
    - name: output  # Shared workspace where the repo and init scripts are located
  steps:
    - name: deploy-mysql
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env sh
        # Apply MySQL deployment with mounted persistent volume and init scripts
        kubectl apply -f $(workspaces.output.path)/tekton/pipeline/mysql-deployment-with-init.yml
   
    - name: wait-for-mysql
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env sh
        # Wait for the MySQL pod to be ready before proceeding
        MYSQL_POD=$(kubectl get pod -l app=mysql -o jsonpath='{.items[0].metadata.name}')
        while [ "$(kubectl get pod $MYSQL_POD -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}')" != "True" ]; do
          echo "Waiting for MySQL pod to be ready..."
          sleep 5
        done
        echo "MySQL pod is ready."

    - name: copy-init-scripts
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env sh
        # Copy initialization SQL scripts into the MySQL container
        kubectl cp $(workspaces.output.path)/src/main/resources/db/mysql/. $(kubectl get pod -l app=mysql -o jsonpath="{.items[0].metadata.name}"):/docker-entrypoint-initdb.d/
        echo "Copied init scripts. Waiting 10 seconds for MySQL to recognize the scripts..."
        sleep 10

    - name: verify-init-scripts
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env sh
        MYSQL_POD=$(kubectl get pod -l app=mysql -o jsonpath='{.items[0].metadata.name}')
        echo "Verifying existence of init scripts in MySQL pod $MYSQL_POD"
        kubectl exec $MYSQL_POD -- ls -la /docker-entrypoint-initdb.d/

    - name: execute-init-scripts
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env sh
        MYSQL_POD=$(kubectl get pod -l app=mysql -o jsonpath='{.items[0].metadata.name}')
        kubectl exec $MYSQL_POD -- ls /docker-entrypoint-initdb.d/
        for script in $(kubectl exec $MYSQL_POD -- sh -c 'ls /docker-entrypoint-initdb.d/'); do
          echo "Executing $script in MySQL pod $MYSQL_POD"
          kubectl exec $MYSQL_POD -- sh -c "mysql -u root < /docker-entrypoint-initdb.d/$script"
        done
