apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  description: |
    This pipeline clones a git repo, then builds db and app
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
  workspaces:
    - name: shared-workspace
      description: |
        This workspace contains the cloned repo files, so they can be read by the next task
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: deploy-mysql
      runAfter: ["checkout"]
      taskRef:
        name: deploy-mysql
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-app
      runAfter: ["deploy-mysql"]  # Ensures this runs after MySQL is deployed
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace
